### ISSUE TITLE
Activity API

### ISSUE THREAD

**Issue by thibauult** [finos/symphony-bdk-python#143]
Goal is to implement a subclass of [`real_time_event_listener.py`](https://github.com/SymphonyPlatformSolutions/symphony-api-client-python/blob/2.0/symphony/bdk/core/service/datafeed/real_time_event_listener.py#L22) which overrides only on_message_sent method.

Implement:

- [ ] a class AbstractActivity with a matcher and on_activity methods.
- [ ] a CommandClass which reacts to on_message_sent only and parses the text inside the received PresentationML
- [ ] a PatternCommand class (subclass of the above) which filters based on a regex
- [ ] a SlashCommand class (subclass of the above) which filters based on a command and optional bot mention.

Take inspiration from the existing [Java BDK Activity API](https://github.com/finos/symphony-bdk-java/blob/main/docs/activity-api.md).

**Comment by symphony-elias** [comment]
Released in 2.0b1
