### ISSUE TITLE
Can jinja2 dependency strict version matching be dropped?

### ISSUE THREAD

**Issue by jenskeiner** [finos/symphony-bdk-python#196]
Hi,

I noticed the PyPi package pulls in `jinja2` as a transitive dependency with an exact version match. This makes it impossible to use the package in the same project together with others that require more recent versions of `jinja2` themselves. Can the strict version requirement be dropped in favor of, say, `>=2.x.x`?

Best,

Jens

**Comment by symphony-youri** [comment]
Hi @jenskeiner,

Which version of `jinja2` are using? In this case as the version 2.11.3 is referenced, _I'm not sure having `>=2.11.3` would allow to use the version 3.0.1 for instance_.  -> Actually it does pick it.

And we would probably avoid setting a lower number than 2.11.3.

**Comment by jenskeiner** [comment]
In the project in question, I have `aiohttp-jinja2==1.4.2` as a dependency which transitively requires `jinja2>=2.10.1`. I also noticed that the latest main branch in the `aiohttp-jinja2` repo already requires 'jinja2>=3.0.0'.

It's a complicated story, not really affecting my argument, I think, but I'm actually not that interested in the `aiohttp-jinja2==1.4.2` dependency directly. It is rather a transitive dependency that I had to add manually due to what I suspect is a bug in another package. But the constraint on `jinja2` there works for me.

I also have `jinja2` as a direct dependency since my own code is using it. I would prefer to use a recent version, e.g. `>=3.0.0`.

However, since `sym-api-client-python` is pinning to the exact version `2.10.1`, I'm forced to use exactly this version. If using this exact version is not really necessary, then I would just like to propose to relax the requirements accordingly, so that newer versions, as long as compatible, can be used as well.

I should add that I'm using `pipenv` to manage dependencies which is quite strict (and rightfully so) when considering the dependency constraints. In my case, dependency resolution fails as soon as I require something newer either directly, or indirectly, e.g. by using a newer version of `aiohttp-jinja2`.

I hope this makes sense.

**Comment by symphony-youri** [comment]
Thanks for the feedback, I just opened https://github.com/SymphonyPlatformSolutions/symphony-api-client-python/pull/205 that should help with that.

**Comment by symphony-youri** [comment]
We just released https://github.com/SymphonyPlatformSolutions/symphony-api-client-python/releases/tag/1.3.5 with this change.

**Comment by jenskeiner** [comment]
Looks good. Thanks for that. I will take a spin shortly.
