### ISSUE TITLE
Deliver a 2.0.0 version in Pypi

### ISSUE THREAD

**Issue by symphony-elias** [finos/symphony-bdk-python#221]
We should deliver a 2.0.0 version in Pypi using the finos user under the new package name `symphony-bdk-python`.

**Comment by symphony-elias** [comment]
Pypi package delivered: https://pypi.org/project/symphony-bdk-python/2.0.0/

**Comment by symphony-youri** [comment]
Shall we close it?

**Comment by symphony-elias** [comment]
Delivered in Pypi: https://pypi.org/project/symphony-bdk-python/2.0.0/
