### ISSUE TITLE
Support custom properties in BDK Configuration file

### ISSUE THREAD

**Issue by chungie55** [finos/symphony-bdk-python#225]
Is there any way for developers to extend or add additional properties to the file for other bot logic usage? Can they still use the BdkConfig class to retrieve these custom properties? This will avoid developers having to load and maintain another config file just for their own bot logic.

How about allowing developers to put their custom properties under a special root in the config, such as “custom” root. Then, they can access them via config.custom.get(“xxx”)?

**Comment by symphony-youri** [comment]
My personal take (so open for discussion) on this would be that the BDK acts as a SDK and is less opinionated than a framework (compared to the Spring Boot integration of the Java BDK for instance). It should not come for his set of conventions  or enforces a way to configure your application. As a bot developer you are then free to configure your application anyway you'd like.

**Comment by symphony-youri** [comment]
Closing this inactive issue.
